Acknowledge data sources
mponce0/covid19.analytics pull request #7
Opened 2020-08-25 18:14 UTC by crispaSLHS

Add some flags to suppress the message() and header() calls.

I made them non-default so that the changes are non-breaking.

This should help silence automated runs of scripts that use the library by allowing the users to pre-acknowledge the sources of the data before moving the scripts to production.  A silent script is helpful when automating with cron so that cron reports can be exceptional and prevent alert fatigue.

2020-08-25 20:44 UTC, mponce0 commented
Hi Andrew,

Thanks for this, it was on my to do list for next releases.
Just one suggestion, would you think of making "acknowledge" representative of "acknowledging" where the data is coming from? I.e. applied to the function more than the 'acknowledgment of the user", so that instead of setting it to FALSE it would be TRUE by default (so that keeps backwards compatibility with previous versions) and it?

2020-08-25 20:53 UTC, crispaSLHS commented
Hi mponce0,

I modeled it after a similar construct I've seen in other places.  The 'acknowledge' flag is to indicate that the user knows what they are doing and have already done the due diligence necessary.  By having the default to FALSE, the user indicates (because they haven't read the documentation) that they don't know where the data is originating.  The messages only show up when the flag is FALSE, mimicking the original behaviour.  Once the user flips it to TRUE, it shortcuts past the messages.  Old code will fall into the default state and new code can make the choice.

Thanks,
Andrew

2020-08-25 22:26 UTC, mponce0 requested changes
OK, sounds good... just a minor thing, in the description of the "acknowledge" argument there is a minor typo 'date' -> 'data'

2020-08-26 13:24 UTC, crispaSLHS commented
I updated the four lines with that typo.

2020-08-26 16:41 UTC, mponce0 approved these changes
Great! Many thanks Andrew!

Best, Marcelo

2020-08-26 16:45 UTC, merged